#!/bin/bash
filename=${1%.*}
echo $filename
java -jar /opt/redtamarin/asc.jar -AS3 -import /opt/redtamarin/builtin.abc -import /opt/redtamarin/toplevel.abc -exe /opt/redtamarin/redshell $1
mv ${filename}.exe ${filename}Compiled
chmod +x ${filename}Compiled

